name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Package and Test
        run: |
          # The -f flag tells Maven where to find the pom.xml file
          mvn -B clean package -f ./url-shortener/pom.xml -DskipTests
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get Project Version
        id: get-version
        run: |
          # Use the -f flag here too to get the correct version
          echo "VERSION=$(mvn -f ./url-shortener/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./url-shortener
          file: ./url-shortener/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:${{ env.VERSION }}